//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp.Quic.Resources
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp.Quic.Resources.Strings", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 Authentication failed because the platform does not support ephemeral keys. 的本地化字符串。
        /// </summary>
        internal static string net_auth_ephemeral
        {
            get
            {
                return ResourceManager.GetString("net_auth_ephemeral", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Authentication failed because the remote party sent a TLS alert: &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string net_auth_tls_alert
        {
            get
            {
                return ResourceManager.GetString("net_auth_tls_alert", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The AddressFamily {0} is not valid for the {1} end point, use {2} instead. 的本地化字符串。
        /// </summary>
        internal static string net_InvalidAddressFamily
        {
            get
            {
                return ResourceManager.GetString("net_InvalidAddressFamily", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The supplied {0} is an invalid size for the {1} end point. 的本地化字符串。
        /// </summary>
        internal static string net_InvalidSocketAddressSize
        {
            get
            {
                return ResourceManager.GetString("net_InvalidSocketAddressSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 This method may not be called when another {0} operation is pending. 的本地化字符串。
        /// </summary>
        internal static string net_io_invalidnestedcall
        {
            get
            {
                return ResourceManager.GetString("net_io_invalidnestedcall", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 QuicConnection is configured to not accept any streams. 的本地化字符串。
        /// </summary>
        internal static string net_quic_accept_not_allowed
        {
            get
            {
                return ResourceManager.GetString("net_quic_accept_not_allowed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A specified application protocol is already in use. 的本地化字符串。
        /// </summary>
        internal static string net_quic_alpn_in_use
        {
            get
            {
                return ResourceManager.GetString("net_quic_alpn_in_use", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Application layer protocol negotiation error was encountered. 的本地化字符串。
        /// </summary>
        internal static string net_quic_alpn_neg_error
        {
            get
            {
                return ResourceManager.GetString("net_quic_alpn_neg_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Authentication failed: {0}. 的本地化字符串。
        /// </summary>
        internal static string net_quic_auth
        {
            get
            {
                return ResourceManager.GetString("net_quic_auth", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 User configured callback failed. 的本地化字符串。
        /// </summary>
        internal static string net_quic_callback_error
        {
            get
            {
                return ResourceManager.GetString("net_quic_callback_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The remote certificate is invalid because of errors in the certificate chain: {0} 的本地化字符串。
        /// </summary>
        internal static string net_quic_cert_chain_validation
        {
            get
            {
                return ResourceManager.GetString("net_quic_cert_chain_validation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The remote certificate was rejected by the provided RemoteCertificateValidationCallback. 的本地化字符串。
        /// </summary>
        internal static string net_quic_cert_custom_validation
        {
            get
            {
                return ResourceManager.GetString("net_quic_cert_custom_validation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The connection timed out from inactivity. 的本地化字符串。
        /// </summary>
        internal static string net_quic_connection_idle
        {
            get
            {
                return ResourceManager.GetString("net_quic_connection_idle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 The server refused the connection. 的本地化字符串。
        /// </summary>
        internal static string net_quic_connection_refused
        {
            get
            {
                return ResourceManager.GetString("net_quic_connection_refused", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Connection aborted by peer ({0}). 的本地化字符串。
        /// </summary>
        internal static string net_quic_connectionaborted
        {
            get
            {
                return ResourceManager.GetString("net_quic_connectionaborted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 CipherSuitePolicy must specify at least one cipher supported by QUIC. 的本地化字符串。
        /// </summary>
        internal static string net_quic_empty_cipher_suite
        {
            get
            {
                return ResourceManager.GetString("net_quic_empty_cipher_suite", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Connection handshake was canceled due to the configured timeout of {0} seconds elapsing. 的本地化字符串。
        /// </summary>
        internal static string net_quic_handshake_timeout
        {
            get
            {
                return ResourceManager.GetString("net_quic_handshake_timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; should be within [0, {1}) range. 的本地化字符串。
        /// </summary>
        internal static string net_quic_in_range
        {
            get
            {
                return ResourceManager.GetString("net_quic_in_range", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An internal error has occurred. {0} 的本地化字符串。
        /// </summary>
        internal static string net_quic_internal_error
        {
            get
            {
                return ResourceManager.GetString("net_quic_internal_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be specified to accept the connection. 的本地化字符串。
        /// </summary>
        internal static string net_quic_not_null_accept_connection
        {
            get
            {
                return ResourceManager.GetString("net_quic_not_null_accept_connection", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Server must provide a certificate in &apos;{0}&apos; or &apos;{1}&apos; or via &apos;{2}&apos; for the connection. 的本地化字符串。
        /// </summary>
        internal static string net_quic_not_null_ceritifcate
        {
            get
            {
                return ResourceManager.GetString("net_quic_not_null_ceritifcate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be specified to start the listener. 的本地化字符串。
        /// </summary>
        internal static string net_quic_not_null_listener
        {
            get
            {
                return ResourceManager.GetString("net_quic_not_null_listener", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be specified and contain at least one item to establish the connection. 的本地化字符串。
        /// </summary>
        internal static string net_quic_not_null_not_empty_connection
        {
            get
            {
                return ResourceManager.GetString("net_quic_not_null_not_empty_connection", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be specified and contain at least one item to start the listener. 的本地化字符串。
        /// </summary>
        internal static string net_quic_not_null_not_empty_listener
        {
            get
            {
                return ResourceManager.GetString("net_quic_not_null_not_empty_listener", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be specified to open the connection. 的本地化字符串。
        /// </summary>
        internal static string net_quic_not_null_open_connection
        {
            get
            {
                return ResourceManager.GetString("net_quic_not_null_open_connection", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Operation aborted. 的本地化字符串。
        /// </summary>
        internal static string net_quic_operationaborted
        {
            get
            {
                return ResourceManager.GetString("net_quic_operationaborted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; must be a power of 2. 的本地化字符串。
        /// </summary>
        internal static string net_quic_power_of_2
        {
            get
            {
                return ResourceManager.GetString("net_quic_power_of_2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A QUIC protocol error was encountered. 的本地化字符串。
        /// </summary>
        internal static string net_quic_protocol_error
        {
            get
            {
                return ResourceManager.GetString("net_quic_protocol_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Reading has been aborted on the stream. 的本地化字符串。
        /// </summary>
        internal static string net_quic_reading_aborted
        {
            get
            {
                return ResourceManager.GetString("net_quic_reading_aborted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Reading is not allowed on stream. 的本地化字符串。
        /// </summary>
        internal static string net_quic_reading_notallowed
        {
            get
            {
                return ResourceManager.GetString("net_quic_reading_notallowed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not supported by System.Net.Quic. 的本地化字符串。
        /// </summary>
        internal static string net_quic_ssl_option
        {
            get
            {
                return ResourceManager.GetString("net_quic_ssl_option", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Stream aborted by peer ({0}). 的本地化字符串。
        /// </summary>
        internal static string net_quic_streamaborted
        {
            get
            {
                return ResourceManager.GetString("net_quic_streamaborted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Connection timed out waiting for a response from the peer. 的本地化字符串。
        /// </summary>
        internal static string net_quic_timeout
        {
            get
            {
                return ResourceManager.GetString("net_quic_timeout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Timeout can only be set to &apos;System.Threading.Timeout.Infinite&apos; or a value &gt; 0. 的本地化字符串。
        /// </summary>
        internal static string net_quic_timeout_use_gt_zero
        {
            get
            {
                return ResourceManager.GetString("net_quic_timeout_use_gt_zero", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Could not use a TLS version required by Quic. TLS 1.3 may have been disabled in the registry. 的本地化字符串。
        /// </summary>
        internal static string net_quic_tls_version_notsupported
        {
            get
            {
                return ResourceManager.GetString("net_quic_tls_version_notsupported", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 &apos;{0}&apos; in not supported remote endpoint type, expected IP or DNS endpoint.&quot; 的本地化字符串。
        /// </summary>
        internal static string net_quic_unsupported_endpoint_type
        {
            get
            {
                return ResourceManager.GetString("net_quic_unsupported_endpoint_type", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A version negotiation error was encountered. 的本地化字符串。
        /// </summary>
        internal static string net_quic_ver_neg_error
        {
            get
            {
                return ResourceManager.GetString("net_quic_ver_neg_error", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Writing has been aborted on the stream. 的本地化字符串。
        /// </summary>
        internal static string net_quic_writing_aborted
        {
            get
            {
                return ResourceManager.GetString("net_quic_writing_aborted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Writing is not allowed on stream. 的本地化字符串。
        /// </summary>
        internal static string net_quic_writing_notallowed
        {
            get
            {
                return ResourceManager.GetString("net_quic_writing_notallowed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 System.Net.Quic is not supported on this platform: {0} For more information see: https://learn.microsoft.com/dotnet/fundamentals/networking/quic/quic-overview#platform-dependencies 的本地化字符串。
        /// </summary>
        internal static string SystemNetQuic_PlatformNotSupported
        {
            get
            {
                return ResourceManager.GetString("SystemNetQuic_PlatformNotSupported", resourceCulture);
            }
        }

        internal static string Format(string resourceFormat, params object[] args)
        {
            if (args != null)
            {
                return string.Format(resourceFormat, args);
            }
            return resourceFormat;
        }
    }
}
